import { Inter } from "next/font/google";
import "./globals.css";
import SidebarDatabase from './components/SidebarDatabase';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen overflow-hidden">
          <SidebarDatabase />
          <div className="flex-1 p-4 overflow-y-auto sm:ml-64">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
